desenvolve06/r6_moovie_app

- lib/models/MoviesModel.dart
Criado a classe filme já adequada para reutilização no projeto quando for consumir API do TMDB.
> feat:[R6-64] Create model movies

- lib/main.dart
- lib/presentation/screens/movies_details_screen.dart
Este PR adiciona a tela de detalhes.
> Added: [R6 -78] Adiciona a tela de detalhes

- lib/main.dart
- lib/presentation/screens/movie_screen.dart
- lib/presentation/screens/movies_details_screen.dart
Este PR adiciona a navegação para a tela de detalhes
> Added: [R6-79] Adiciona a navegação para a tela de detalhes

- lib/main.dart
- lib/presentation/components/appBar_main.dart
- lib/presentation/screens/movie_screen.dart
- lib/presentation/screens/movies_details_screen.dart
Este PR refatora o app Bar para ser reutilizado nas outras telas do app
[R¨-82](https://trello.com/c/ii1NLU4l/82-r6-82-refatorar-a-appbarmain-para-ser-utilizado-para-as-outras-telas)
> Refatored: [R6-82] Refatora componente app bar

- lib/data/error/exceptions.dart
- lib/data/error/failure.dart
- lib/data/network/error_message_model.dart
- lib/main.dart
- lib/presentation/components/details/media_detail_header.dart
- lib/presentation/components/home/appBar_main.dart
- lib/presentation/components/home/banner_list.dart
- lib/presentation/components/home/media_list.dart
- lib/presentation/components/home/navBar_main.dart
- lib/presentation/components/home/search_bar_app.dart
- lib/presentation/pages/series_details_screen.dart
- lib/presentation/pages/splash_screen.dart
- lib/resources/app_colors.dart
- lib/resources/app_fonts.dart
- lib/resources/app_strings.dart
- lib/resources/app_values.dart
Adicionando constantes no projeto.
Link do Trello: [https://trello.com/c/1bokLpnr/86-r6-86-criar-arquivos-para-as-constantes-para-strings-e-colors](https://trello.com/c/1bokLpnr/86-r6-86-criar-arquivos-para-as-constantes-para-strings-e-colors)
> Feature/r6 86/add constants

- lib/domain/entities/series.dart
- lib/domain/repository/movie_repository.dart
- lib/injection/injection.dart
- lib/presentation/components/home/search_bar_app.dart
- lib/presentation/pages/main_screen.dart
- lib/presentation/pages/splash_screen.dart
Este PR adiciona pequenas melhorias como limpeza de importas e otimização da tela da main.
> Added: [R-90] Adiciona melhorias no projeto - Part 1

- README.md
Add project instructions and informations
> chore: [R6-92]updated README.md

- lib/presenter/widgets/home/media_list.dart
- lib/presenter/widgets/home/toogle_favorite.dart
Este PR cria a interface  toggle para favoritar o filme e série nas listas
[R6-91](https://trello.com/c/DD3mtnjI/91-r6-91-criar-o-componente-favoritos-e-chama-na-lista)
> Added:[R6-91] Cria botão para os Favoritos 

- lib/data/network/source/local/movies/local_data_source_impl.dart
- lib/data/network/source/local/series/local_data_source_impl.dart
- lib/domain/entities/movie.dart
- lib/presenter/bloc/favorites/favorite_bloc.dart
- lib/presenter/pages/favorites_screen.dart
- lib/presenter/pages/main_screen.dart
Correção de Problema ao Adicionar e Remover Favoritos.
> Fix: fix issue with adding and removing movies and series from favorites

- lib/domain/entities/movie.dart
- lib/domain/usecase/movies/is_favorite_use_case.dart
- lib/main.dart
- lib/presenter/bloc/favorites/favorite_bloc.dart
- lib/presenter/bloc/favorites/favorite_state.dart
- lib/presenter/pages/favorites_screen.dart
- lib/presenter/pages/login_page.dart
- lib/presenter/pages/movies_details_screen.dart
- lib/presenter/pages/series_details_screen.dart
- lib/presenter/pages/splash_screen.dart
- lib/presenter/widgets/details/arch_banner_image.dart
- lib/presenter/widgets/details/media_detail_header.dart
- lib/presenter/widgets/home/app_bar_main.dart
- lib/presenter/widgets/home/banner_list.dart
- lib/presenter/widgets/home/media_list.dart
- lib/presenter/widgets/home/nav_bar_main.dart
- lib/presenter/widgets/home/search_bar_app.dart
Correções de imports, consts e comentários não utilizados.
3 avisos em relação aos favoritos coloquei para ignorar o aviso, pois como foi ideia de outra pessoa fazendo aquilo, não sei onde seria usado
tem um texto no card e no slack com o pedido da mentora para essas correções irem para essa entrega
https://trello.com/c/Ry1VEa9u/114-r6-114-corre%C3%A7%C3%B5es-do-feedback-da-isadora
> Refactor: [R6-114] Remove imports  e comentários

- README.md
- lib/presenter/pages/movies_details_screen.dart
- lib/presenter/pages/series_details_screen.dart
- lib/presenter/widgets/details/review.dart
- lib/presenter/widgets/home/search_bar_app.dart
- lib/utils/utils.dart
- gerência dos favoritos
- search 
- readme
- remove problemas
> Added: [R6-119]: manage favorites

- lib/main.dart
- lib/presenter/pages/main_screen.dart
- pubspec.lock
Este PR corrige bug ao clicar na busca de pesquisa no bottom navigation o componente estava sendo chamado novamente e visualmente aparecia duplicado. O componente Search foi movido para a screen main e removido a chamada duplicada da main
* Antes
* Após a correção
> Fixed:[R6-trivial] Corrige  a  navegação ao campo de pesquisa no bottom  navigation

- lib/presenter/pages/favorites_screen.dart
- lib/presenter/pages/movies_details_screen.dart
- lib/presenter/pages/series_details_screen.dart
- lib/presenter/widgets/home/banner_list.dart
- lib/presenter/widgets/home/card_image.dart
- lib/presenter/widgets/home/card_image_text.dart
- lib/presenter/widgets/home/card_text.dart
- lib/presenter/widgets/home/favorite_toggle_button.dart
- lib/presenter/widgets/home/media_list.dart
Este PR separa componentes de widgets das listas de filmes e series na tela inicial do app.
[R6-115](https://trello.com/c/ZfAFW0JH/115-r6-115-componentizar-widgets-do-medialist)
> Refactored: [R6-115] Componentiza  widgets das listas de filmes e series

- pubspec.lock
- pubspec.yaml
- test/domain/usecase/movies/add_to_favorites_use_case_test.dart
- test/domain/usecase/movies/get_favorites_use_case_test.dart
- test/utils/class_mock.dart
Cria o teste do GetFavoritesUseCase.
> Added: Cria o teste de GetFavoritesUseCase

- pubspec.lock
- pubspec.yaml
- test/domain/usecase/movies/add_to_favorites_use_case_test.dart
- test/utils/class_mock.dart
Implementa o teste do AddFavoritesUseCase.
> Added: Cria o teste do AddFavoritesUseCase

- lib/presenter/widgets/home/BannerItem.dart
- lib/presenter/widgets/home/banner_list.dart
- lib/presenter/widgets/home/banner_text.dart
Este PR componentiza os widgets da lista de series banner
[R6-120](https://trello.com/c/Mhooku5i/120-r6-120-componentizar-os-widgets-do-banners-list)
> Refactored: [R6-120] Componetiza widgets banner lista

- test/data/repository/movie_repository_impl_test.dart
- test/data/repository/series_repository_impl_test.dart
- test/domain/usecase/movies/get_popular_movie_use_case_test.dart
- test/domain/usecase/movies/is_favorite_use_case_test.dart
- test/domain/usecase/movies/remove_from_favorite_use_case_test.dart
- test/domain/usecase/series/add_to_favorites_use_case_test.dart
- test/domain/usecase/series/get_favorites_use_case_test.dart
- test/domain/usecase/series/get_popular_series_use_case_test.dart
- test/domain/usecase/series/is_favorite_use_case_test.dart
- test/domain/usecase/series/remove_from_favorite_use_case_test.dart
- test/utils/class_mock.dart
Adiciona os seguintes testes unitários:
- get_popular_movie_use_case
- is_favorite_use_case
- remove_from_favorite_use_case
- movie_repository_impl
- series_repository_impl
- add_to_favorites_use_case_series
- get_favorites_use_case_series
- get_popular_series_use_case
- is_favorite_serie_use_case
- remove_serie_from_favorite_use_case
Todos estão estruturados na pasta de testes.
> [R6-122] Added Unit Tests

- pubspec.lock
- pubspec.yaml
- test/presenter/card_image_widget_test.dart
- test/presenter/card_text_widget_test.dart
- test/stubs/stub.dart
Este PR Adiciona testes de widgets para cardImage e cardText na camda presenter.
> Added: [R6-121] Adiciona testes de widgets para cardImage e cardText

- lib/presenter/widgets/home/card_image_text.dart
- lib/presenter/widgets/home/favorite_bloc_builder.dart
- test/presenter/favorite_bloc_builder_test.dart
- test/presenter/nav_bar_main_test.dart
Este PR Adiciona  testes unitários de  widgets FavoriteblocBuilder e a interface do usuário dos  botões da nav Bar
> Added: [R6-130] Adiciona  testes unitários de  widgets blocbuilder e nav bar

- .gitignore
- pubspec.yaml
- test/data/integration_test/movie_api_test.dart
- test/data/integration_test/serie_api_test.dart
- test/presenter/nav_bar_main_test.dart
- test/utils/favorite_bloc_mock.dart
Criando o PR para os seguintes testes de integração:
- movie_api_test.dart
- serie_api_test.dart
Task: [https://trello.com/c/p2D3Che9/126-testes-de-integra%C3%A7%C3%A3o](https://trello.com/c/p2D3Che9/126-testes-de-integra%C3%A7%C3%A3o)
> Added:[R6 -126] add integration api test movie series

- README.md
> Added[R6-trivial]: atualiza a documentação
